server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 192.168.118.128
    username: leyou
    password: 123456
    virtual-host: /leyou
leyou:
  sms:
    accessKeyId: LTAI4FeY7Wtfht4dz38HL5Nw # 你自己的accessKeyId
    accessKeySecret: DvLkqsEmGI4zMXr9bzW20dWD5UqFls # 你自己的AccessKeySecret
    signName: 乐优商城 # 签名名称
    verifyCodeTemplate: SMS_181866043 # 模板名称