 server:
  port: 8088
 spring:
  application:
    name: cart-service
  redis:
    host: 192.168.118.128
 eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true # 返回eureka的是ip，而不是主机名
    ip-address: 127.0.0.1 # 设置返回的ip是啥
    instance-id: ${spring.application.name}:${server.port}
 leyou:
   jwt:
     pubKeyPath: F:/heima/rsa/rsa.pub # 公钥地址
     cookieName: LY_TOKEN


